services:
  database:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lrr_suiviestage
    ports:
      # Expose le port 3306 vers ton Linux
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql

volumes:
  database_data:
